### ISSUE TITLE
Engine request for RPM change from control message to engine structure message

### ISSUE THREAD

**Issue by daan-laixer** [Laixer/Pixelbot#6]
Currently a control message is used to request an RPM change, this needs to be changed to an engine structure message

**Comment by DonZandbergen** [comment]
![image](https://github.com/Laixer/Pixelbot/assets/46600362/bfff52a1-43b2-4b41-9c05-a2df35448856)

@daan-laixer Wat moet er ipv de 1-9 komen?

**Comment by daan-laixer** [comment]
> ![image](https://private-user-images.githubusercontent.com/46600362/328439396-bfff52a1-43b2-4b41-9c05-a2df35448856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzAzNjgsIm5iZiI6MTcxNTA3MDA2OCwicGF0aCI6Ii80NjYwMDM2Mi8zMjg0MzkzOTYtYmZmZjUyYTEtNDNiMi00YjQxLTljMDUtYTJkZjM1NDQ4ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA4MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NGY0MDY1M2ZiMzYyYTY0M2ZmOTg2MTI5YmJkM2E0MzAwN2M3OTQ5MGZhZGQ1NzcyMGQzNzMyZmQ3MTZkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.frM6e9V6VVjOTK-rHVPJ9_rxa9qVMxbyJwktiPqzO4I)
> 
> @daan-laixer Wat moet er ipv de 1-9 komen?

Ik zal dit beantwoorden in een andere issue, deze issue is niet gerelateerd

**Comment by daan-laixer** [comment]
Fixed in 42e3cf6aa9b93958c5bcd67ab06f21d59e191f49

**Comment by daan-laixer** [comment]
Tested on raspberry pi, glonax version on excavator is not yet up to date, 3.5.5 -> 3.5.6
