### ISSUE TITLE
Get work mode from slider after engine request

### ISSUE THREAD

**Issue by daan-laixer** [Laixer/Pixelbot#7]
Currently, when motion is locked or when motor is in shutdown, the physical slider can move but the UI slider cannot. When the motion is resumed or when the motor is started the slider must first be moved to the previously requested rpm / workmode before the rpm/work mode can be changed. Instead we want to read the current slider value and change the rpm/workmode directly.

**Comment by DonZandbergen** [comment]
related to #8
