### ISSUE TITLE
Calibration for joypads

### ISSUE THREAD

**Issue by daan-laixer** [Laixer/Pixelbot#9]
The joypads need calibration for the joysticks, one of our current joystick has an offset, and left and right joysticks need to be configurable.

**Comment by DonZandbergen** [comment]
Implement on settings modal.

**Comment by DonZandbergen** [comment]
Also: implement setting for configuring left of right joystick to l eft of right controle

**Comment by daan-laixer** [comment]
offset not now, additionally, make sensitivity configurable, might be an option in godot
